### ISSUE TITLE
port numbers for forked procs

### ISSUE THREAD

**Issue by kablamo** [brummett/Devel-hdb#101]
If I debug an app that forks, hdb creates a new connection on a new port.  These port numbers are often high numbers like 44333.  But my servers only have port numbers in a certain range available.  It might make sense to use a port number which is the same as the user passed in on the command line + 1 instead of some random high number port.

**Comment by brummett** [comment]
Current code relies on the system to pick a port for us
https://github.com/brummett/Devel-hdb/blob/20950339b748456a1c5889a593bd18ebaa13b99c/lib/Devel/hdb/App.pm#L221

Is it that it's picking a port that's invalid for the system (which would be some kind of bug), or that a system policy is preventing you from connecting to it (maybe a firewall or something)?

If it's the latter, there's no guarantee that port+1 will be available to use.  The best I could do is keep incrementing the port number by 1 until it works, and give up after 10 or 20 attempts.

**Comment by kablamo** [comment]
hdb successfully creates the new connection on the new high number port.  It is a firewall thats blocking that port for me.  What you said would be great: increment the port number passed in by the user by 1.  

Its true its not guaranteed to be available, but its more likely.  Companies often allow certain blocks of ports to be available.

**Comment by brummett** [comment]
Could you pull the child-process-port branch from https://github.com/brummett/Devel-hdb/pull/102 and make sure it solves you problem before I merge it?
