### ISSUE TITLE
Show something reasonable when multiple statements on the same line

### ISSUE THREAD

**Issue by brummett** [brummett/Devel-hdb#3]
For a line like
foo(); bar(); 4
or
if (foo() > bar() )

We'd like the current position to show which part of that line will be the next to execute.  It will probably involve inspecting the optree

**Comment by brummett** [comment]
This would require support for reporting the callsite in Locations for Devel::Chitin, then passing along that info through the rest API and displaying it to the user.

**Comment by rocky** [comment]
Ok. Do it!

**Comment by brummett** [comment]
This is working, at least in a minimal way, via Devel::Chitin 0.9 and #113
